# https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
# https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
name: "j1603_16__manual"
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options:
          - monalisa
          - cschleiden
        required: false
      message:
        required: true
        description: message description
      use-emoji:
        type: boolean
        description: Include  emojis
        required: false
      environment:
        type: environment
        required: false
        description: environment description

      # New, de facto used
      AUTOMATON__1603_16__CPLP_UNICAE:
        # type: boolean
        type: choice
        description: AUTOMATON__1603_16__CPLP_UNICAE
        options:
          - "1"
          - "0"
        required: false
      ARTIFICIAL_THROTTLING:
        type: string
        description: ARTIFICIAL_THROTTLING
        required: false
      UNM49_INITIALI:
        type: string
        description: UNM49_INITIALI
        required: false
      UNM49_FINALI:
        type: string
        description: UNM49_FINALI
        required: false

    # # This syntax is invalid, not allowed here
    # secrets:
    #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY__ID_ED25519__GITHUBRUNNER2022 }}

# env:
#   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY__ID_ED25519__GITHUBRUNNER2022 }}

# jobs:
#   do-it:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Run a one-line script
#         run: echo Hello, world!

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"

  reusable_workflow_job:
    uses: ./.github/workflows/r1603_16__NNN-NNN.yml
    with:
      AUTOMATON__1603_16__CPLP_UNICAE: ${{ inputs.AUTOMATON__1603_16__CPLP_UNICAE }}
      ARTIFICIAL_THROTTLING: ${{ inputs.ARTIFICIAL_THROTTLING }}
      UNM49_INITIALI: ${{ inputs.UNM49_INITIALI }}
      UNM49_FINALI: ${{ inputs.UNM49_FINALI }}
      # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY__ID_ED25519__GITHUBRUNNER2022 }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY__ID_ED25519__GITHUBRUNNER2022 }}

    # runs-on: ubuntu-latest
    # # environment: production
    # steps:
    #   - uses: actions/checkout@v3

    #   # Uses same repository, but need specify organization and repository
    #   - uses: EticaAI/MDCIII-boostrapper/.github/workflows/r1603_16__NNN-NNN.yml@main
    #     with:
    #       AUTOMATON__1603_16__CPLP_UNICAE: ${{ inputs.AUTOMATON__1603_16__CPLP_UNICAE }}
    #       ARTIFICIAL_THROTTLING: ${{ inputs.ARTIFICIAL_THROTTLING }}
    #       UNM49_INITIALI: ${{ inputs.UNM49_INITIALI }}
    #       UNM49_FINALI: ${{ inputs.UNM49_FINALI }}
    #       # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #       SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY__ID_ED25519__GITHUBRUNNER2022 }}

  # reusable_workflow_job:
  #   runs-on: ubuntu-latest
  #   # environment: production
  #   steps:
  #     - uses: actions/checkout@v3

  #     # Uses same repository, but need specify organization and repository
  #     - uses: EticaAI/MDCIII-boostrapper/.github/workflows/r1603_16__NNN-NNN.yml@main
  #       with:
  #         AUTOMATON__1603_16__CPLP_UNICAE: ${{ inputs.AUTOMATON__1603_16__CPLP_UNICAE }}
  #         ARTIFICIAL_THROTTLING: ${{ inputs.ARTIFICIAL_THROTTLING }}
  #         UNM49_INITIALI: ${{ inputs.UNM49_INITIALI }}
  #         UNM49_FINALI: ${{ inputs.UNM49_FINALI }}
  #         # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY__ID_ED25519__GITHUBRUNNER2022 }}
