name: "aN1603_16"

on:
  push:
    branches:
      - main

env:
  TERM: xterm
  AUTOMATON__1603_16__CPLP_UNICAE: "0"
  ARTIFICIAL_THROTTLING: 0
  UNM49_INITIALI: 0
  UNM49_FINALI: 100

defaults:
  run:
    working-directory: ./officina

# jobs:
#   reusable_workflow_job:
#     runs-on: ubuntu-latest
#     # environment: production
#     steps:
#       # - uses: ./.github/workflows/my-action
#       - uses: ./.github/workflows/r1603_16__NNN-NNN.yml
#         with:
#           username: ${{ inputs.username }}
#           token: ${{ secrets.envPAT }}

jobs:

  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  call-workflow-passing-data:
    # uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    uses: ./.github/workflows/r1603_16__NNN-NNN.yml
    with:
      username: mona
      tag: tagnumber
    secrets:
      envPAT: teste123
      # envPAT: ${{ secrets.envPAT }}
