name: "j1603_16__0_100"

on:
  push:
    branches:
      - main

env:
  TERM: xterm
  AUTOMATON__1603_16__CPLP_UNICAE: "0"
  ARTIFICIAL_THROTTLING: 0
  UNM49_INITIALI: 0
  UNM49_FINALI: 100

defaults:
  run:
    working-directory: ./officina

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  call-workflow-passing-data:
    # uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    uses: ./.github/workflows/r1603_16__NNN-NNN.yml
    with:
      username: mona
    #   tag: tagnumber
    # secrets:
    #   envPAT: teste123
    #   # envPAT: ${{ secrets.envPAT }}

  reusable_workflow_job111:
    uses: ./.github/workflows/r1603_16__NNN-NNN.yml
    with:
      AUTOMATON__1603_16__CPLP_UNICAE: ${{ inputs.AUTOMATON__1603_16__CPLP_UNICAE }}
      ARTIFICIAL_THROTTLING: ${{ inputs.ARTIFICIAL_THROTTLING }}
      UNM49_INITIALI: ${{ inputs.UNM49_INITIALI }}
      UNM49_FINALI: ${{ inputs.UNM49_FINALI }}
      # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY__ID_ED25519__GITHUBRUNNER2022 }}

  # reusable_workflow_job333:
  #   runs-on: ubuntu-latest
  #   # environment: production
  #   steps:
  #     # Uses same repository, but need specify organization and repository
  #     - uses: EticaAI/MDCIII-boostrapper/.github/workflows/r1603_16__NNN-NNN.yml@main
  #       with:
  #         AUTOMATON__1603_16__CPLP_UNICAE: ${{ inputs.AUTOMATON__1603_16__CPLP_UNICAE }}
  #         ARTIFICIAL_THROTTLING: ${{ inputs.ARTIFICIAL_THROTTLING }}
  #         UNM49_INITIALI: ${{ inputs.UNM49_INITIALI }}
  #         UNM49_FINALI: ${{ inputs.UNM49_FINALI }}
  #         # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY__ID_ED25519__GITHUBRUNNER2022 }}

