#===============================================================================
#
#          FILE:  r1603_16__NNN-NNN.yml
#
#         USAGE:  - See https://docs.github.com/en/actions
#                       /learn-github-actions/understanding-github-actions
#                 - See https://docs.github.com/en/actions
#                       /using-workflows/reusing-workflows
#
#   DESCRIPTION:  Reusable workflow (draft)
#       OPTIONS:  ---
#
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Emerson Rocha <rocha[at]ieee.org>
#       COMPANY:  EticaAI
#       LICENSE:  Public Domain dedication or Zero-Clause BSD
#                 SPDX-License-Identifier: Unlicense OR 0BSD
#       VERSION:  v1.0
#       CREATED:  2022-06-21 02:06 UTC started. Based on 1603_16.yml
#      REVISION:  ---
#===============================================================================
# SPDX-License-Identifier: Unlicense OR 0BSD

name: r1603_16__NNN-NNN

on:
  workflow_call:
    inputs:
      username:
        description: "A username passed from the caller workflow"
        default: "john-doe"
        required: false
        type: string
      AUTOMATON__1603_16__CPLP_UNICAE:
        description: "AUTOMATON__1603_16__CPLP_UNICAE"
        default: "1" # "1", "0"
        required: false
        type: string
      ARTIFICIAL_THROTTLING:
        description: "ARTIFICIAL_THROTTLING seconds)"
        default: "0"
        required: false
        type: string # number would be better, but manual run fails
      UNM49_INITIALI:
        description: "UNM49_INITIALI"
        default: "0"
        required: false
        type: string # number would be better, but manual run fails
      UNM49_FINALI:
        description: "UNM49_INITIALI"
        default: "999"
        required: false
        type: string # number would be better, but manual run fails
    secrets:
      # # ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY__ID_ED25519__GITHUBRUNNER2022 }}
      SSH_PRIVATE_KEY:
        required: false

env:
  # Fix: 'tput: No value for $TERM and no -T specified'
  TERM: xterm
  AUTOMATON__1603_16__CPLP_UNICAE: ${{ inputs.AUTOMATON__1603_16__CPLP_UNICAE }}
  ARTIFICIAL_THROTTLING: ${{ inputs.ARTIFICIAL_THROTTLING }}
  UNM49_INITIALI: ${{ inputs.UNM49_INITIALI }}
  UNM49_FINALI: ${{ inputs.UNM49_FINALI }}

# jobs:
#   print-username:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print the input name to STDOUT
#         run: echo The username is ${{ inputs.username }}

# on:
#   workflow_call:
#     inputs:
#       username:
#         type: string
#         required: false
#       tag:
#         type: string
#         required: false
#     # secrets:
#     #   token:
#     #     required: true

# jobs:
#   example_job:
#     name: Pass input and secrets to my-action
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Hello"
#       - name: Set the tag
#         run: |
#           if [ -z "${{inputs.tag}}" ]
#           then
#             echo "final_tag=latest" >> $GITHUB_ENV
#           else
#             echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
#           fi

#   do-something-else:
#     runs-on: ubuntu-latest

#     steps:
#       - run: echo "Hello"

defaults:
  run:
    working-directory: ./officina

jobs:
  "r1603_16__NNN-NNN":
    name: aN1603_16
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      #### Low level ssh-agent _________________________________________________
      # @see https://github.com/marketplace/actions/webfactory-ssh-agent
      # REASONING: this is not necessary for read-only requests to public
      #            repositories, but for use GitHub Actions runner, we need
      #            something far more dynamic than write YAML for every
      #            repository we would create with shell scripting
      - name: ID_ED25519__GITHUBRUNNER2022
        uses: webfactory/ssh-agent@v0.5.4
        # We allow to fail since some commands may only need read-only access
        # @TODO assume that if secrets.SSH_PRIVATE_KEY is undefined, this
        #       task can be skiped
        continue-on-error: true
        with:
          # ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY__ID_ED25519__GITHUBRUNNER2022 }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - run: ssh -T git@github.com
      #   continue-on-error: true

      #### Fetch data __________________________________________________________

      - name: EticaAI/MDCIII-boostrapper
        uses: actions/checkout@v3

      - name: EticaAI/lexicographi-sine-finibus
        uses: actions/checkout@v3
        with:
          repository: EticaAI/lexicographi-sine-finibus
          path: officina/999999/3133368/lexicographi-sine-finibus

      - name: MDCIII/999999_1603_16
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          repository: MDCIII/999999_1603_16
          path: officina/999999/3133368/999999_1603_16

      # Debug part, remove later, START
      - run: pwd
      - run: find * -type f
        continue-on-error: true
      # Debug part, remove later, END

      - name: "Merge 999999 [MDCIII/999999_1603_16 -> EticaAI/lexicographi-sine-finibus]"
        run: >
          rsync --verbose --human-readable --checksum --recursive
          999999/3133368/999999_1603_16/999999/
          999999/3133368/lexicographi-sine-finibus/officina/999999
        continue-on-error: true

      # - name: "Merge 999999 [MDCIII/999999_1603_16 -> EticaAI/lexicographi-sine-finibus]"
      #   run: rsync --dry-run --verbose --human-readable --checksum --recursive officina/999999/3133368/999999_1603_16/999999/ officina/999999/3133368/lexicographi-sine-finibus/officina/999999
      #   continue-on-error: true

      # Debug part, remove later, START
      - run: pwd
      - run: ls -lha
      - run: ls -lha 999999/
        continue-on-error: true
      - run: ls -lha 999999/3133368/
        continue-on-error: true
      - run: find * -type f
        continue-on-error: true
      # Debug part, remove later, END

      ### Symlinks
      - name: officina/1603
        run: >
          ln --relative --symbolic
          999999/3133368/lexicographi-sine-finibus/officina/1603
          1603
        continue-on-error: true

      - name: officina/999999/1603
        run: >
          ln --relative --symbolic
          999999/3133368/lexicographi-sine-finibus/officina/999999/1603
          999999/1603
        continue-on-error: true

      - name: officina/999999999/0
        run: >
          ln --relative --symbolic
          999999/3133368/lexicographi-sine-finibus/officina/999999999/0
          999999999/0
        continue-on-error: true

      # 1603_1_99 is not stored with main repository, but is required by
      # scripts that generate Codex. For now we're simply downloading
      # from the older EticaAI/lsf-cache/ repository
      - name: "Temporary fix [1603/1/99/1603_1_99.no1.tm.hxl.csv]"
        run: >
          curl --output 1603/1/99/1603_1_99.no1.tm.hxl.csv
          https://raw.githubusercontent.com/EticaAI/lsf-cache/main/1603/1/99/1603_1_99.no1.tm.hxl.csv
        continue-on-error: true

      - name: "Temporary fix [999999/1603/45/16/1603_45_16.index.hxl.csv]"
        run: >
          curl --output 999999/1603/45/16/1603_45_16.index.hxl.csv
          https://raw.githubusercontent.com/EticaAI/lsf-cache/main/999999/1603/45/16/1603_45_16.index.hxl.csv
        continue-on-error: true

      - run: ls -lha 1603/1/99/1603_1_99.no1.tm.hxl.csv
        continue-on-error: true

      - run: ls -lha 999999/1603/45/16/1603_45_16.index.hxl.csv
        continue-on-error: true

      #### Python ______________________________________________________________
      # @see https://github.com/actions/setup-python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      # - run: pip install libhxl hxltm-eticaai openpyxl frictionless csvkit
      # - run: pip install -r .github/requirements.txt
      - run: pip install -r ../.github/requirements.txt
        continue-on-error: true

      #### Java Setup __________________________________________________________
      # @see https://github.com/marketplace/actions/setup-java-jdk
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      ### Apache Jena ----------------------------------------------------------
      # @see https://github.com/foooomio/setup-jena
      - uses: foooomio/setup-jena@v2
      - run: sparql --version

      ### Rapper (tool for work with low level RDF) ----------------------------
      - run: sudo apt-get install -y raptor2-utils
        continue-on-error: true

      #### Debug _______________________________________________________________
      # _[por-Latn] Lista arquivos locais (útil para saber o que fazer upload [por-Latn]_
      - run: ls -lha
      # tree-like command for macos, @see https://superuser.com/questions/359723/mac-os-x-equivalent-of-the-ubuntu-tree-command
      - run: find * -type f

      - run: hxltmcli --version
        continue-on-error: true

      - run: riot --version
        continue-on-error: true

      - run: frictionless --version
        continue-on-error: true

      - run: rsync --version
        continue-on-error: true

      ### Debug, internal tools from lexicographi-sine-finibus
      - run: ./999999999/0/1603_1.py --help
        continue-on-error: true

      - run: ./999999999/0/999999999_7200235.py --help
        continue-on-error: true

      - run: ./999999999/0/1603_3_12.py --help
        continue-on-error: true

      #### ssh keys
      # @see https://github.com/webfactory/ssh-agent
      # SSH_PRIVATE_KEY__ID_ED25519__GITHUBRUNNER2022

      # - run: ssh -T git@github.com
      #   continue-on-error: true

      # @TODO beyond bare 'git', also configure gh (GitHub CLI) to use the
      #       machine operator like @eticaaibot, not the human user. See
      # docs.github.com/pt/actions/using-workflows/using-github-cli-in-workflows

      ### 1603_16 ----------------------------------------------------------
      - run: ls -lha 999999/1603/45/16/
        continue-on-error: true

      - run: ls -lha 999999/1603/45/16/1603_45_16.index.hxl.csv
        continue-on-error: true

      - run: ./999999999/999999_1603_16.workflow.sh
        continue-on-error: true

      - run: ./999999999/1603_16.workflow.sh
        continue-on-error: true
